services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tools_challenge'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
