@id = 1234569213

### Realiza estorno
POST http://localhost:8080/transacao/estornar/1345692113

### Consulta transaçao
GET http://localhost:8080/transacao/1345692113

### Cria transação
POST http://localhost:8080/transacao
Content-Type: application/json

{
  "cartao": "************8321",
  "id": "1345692113",
  "descricao": {
    "valor": "100.00",
    "dataHora": "06/08/2024 23:30:00",
    "estabelecimento": "Posto Aldo"
  },
  "formaPagamento": {
    "tipoPagamento": "AVISTA",
    "parcelas": 1
  }
}
